Application/Controllers/UsersAdminController.cs
using Application.App_Start;
using Application.Models;
using Application.ViewModels;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Application.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class UsersAdminController : Controller
    {
        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager,
            ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext()
                    .GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // Add the Group Manager (NOTE: only access through the public
        // Property, not by the instance variable!)
        private ApplicationGroupManager _groupManager;
        public ApplicationGroupManager GroupManager
        {
            get
            {
                return _groupManager ?? new ApplicationGroupManager();
            }
            private set
            {
                _groupManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext()
                    .Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }


        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }


        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            // Show the groups the user belongs to:
            var userGroups = await this.GroupManager.GetUserGroupsAsync(id);
            ViewBag.GroupNames = userGroups.Select(u => u.Name).ToList();
            return View(user);
        }


        public ActionResult Create()
        {
            // Show a list of available groups:
            ViewBag.GroupsList =
                new SelectList(this.GroupManager.Groups, "Id", "Name");
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel,
            params string[] selectedGroups)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    UserName = userViewModel.Email,
                    Email = userViewModel.Email
                };
                var adminresult = await UserManager
                    .CreateAsync(user, userViewModel.Password);

                //Add User to the selected Groups 
                if (adminresult.Succeeded)
                {
                    if (selectedGroups != null)
                    {
                        selectedGroups = selectedGroups ?? new string[] { };
                        await this.GroupManager
                            .SetUserGroupsAsync(user.Id, selectedGroups);
                    }
                    return RedirectToAction("Index");
                }
            }
            ViewBag.GroupsList =
               new SelectList(this.GroupManager.Groups, "Id", "Name");
            ViewBag.Groups = new SelectList(
                await RoleManager.Roles.ToListAsync(), "Id", "Name");
            return View();
        }


        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            // Display a list of available Groups:
            var allGroups = this.GroupManager.Groups;
            var userGroups = await this.GroupManager.GetUserGroupsAsync(id);

            var model = new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email
            };

            foreach (var group in allGroups)
            {
                var listItem = new SelectListItem()
                {
                    Text = group.Name,
                    Value = group.Id,
                    Selected = userGroups.Any(g => g.Id == group.Id)
                };
                model.GroupsList.Add(listItem);
            }
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(
            [Bind(Include = "Email,Id")] EditUserViewModel editUser,
            params string[] selectedGroups)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                // Update the User:
                user.UserName = editUser.Email;
                user.Email = editUser.Email;
                await this.UserManager.UpdateAsync(user);

                // Update the Groups:
                selectedGroups = selectedGroups ?? new string[] { };
                await this.GroupManager.SetUserGroupsAsync(user.Id, selectedGroups);
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }


        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                // Remove all the User Group references:
                await this.GroupManager.ClearUserGroupsAsync(id);

                // Then Delete the User:
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Application/Views/UsersAdmin/Create.cshtml
@model Application.ViewModels.RegisterViewModel
@{
    ViewBag.Title = "新增帳號";
    Layout = "~/Views/Shared/_AdminLte3.cshtml";
}

<div class="container-fluid">
    @using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        <div class="card">
            <div class="card-header">
                帳號基本資料
            </div>
            <div class="card-body">
                <table class="table table-hover table-bordered">
                    <tr>
                        <th style="width:120px">@Html.LabelFor(m => m.Email, new { @class = "control-label" })</th>
                        <td>
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control col-md-4" })
                            @Html.ValidationSummary("", new { @class = "text-error" })
                        </td>
                    </tr>
                    <tr>
                        <th>
                            @Html.LabelFor(m => m.Password, new { @class = "control-label" })
                        </th>
                        <td>
                            @Html.PasswordFor(m => m.Password, new { @class = "form-control col-md-4" })
                        </td>
                    </tr>
                    <tr>
                        <th>
                            @Html.LabelFor(m => m.ConfirmPassword, new { @class = "control-label" })
                        </th>
                        <td>
                            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control col-md-4" })
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="card">
            <div class="card-header">所屬群組</div>
            <div class="card-body">
                <ul>
                    @if (ViewBag.GroupsList != null)
                    {
                        foreach (var item in (SelectList)ViewBag.GroupsList)
                        {
                            <li>
                                <label>
                                    <input type="checkbox" name="selectedGroups" value="@item.Value" class="checkbox-inline" />
                                    @Html.Encode(item.Text)
                                </label>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
        <div class="pb-3">
            <a class="btn btn-warning" href="@Url.Action("Index")"><i class="fas fa-arrow-left"></i>返回</a>
            <button type="submit" class="btn btn-primary">

                <i class="fas fa-save"></i>
                新增
            </button>
        </div>
        
    }

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Application/Views/UsersAdmin/Delete.cshtml
@model Application.Models.ApplicationUser

@{
    ViewBag.Title = "刪除帳號";
    Layout = "~/Views/Shared/_AdminLte3.cshtml";
}



<h3 class="text-danger">⚠️你確定要刪除帳號 @Html.DisplayFor(model => model.UserName) 嗎? ⚠️</h3>
<div> 
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <a class="btn btn-warning" href="@Url.Action("Index")"><i class="fas fa-arrow-left"></i>返回</a>
            <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i> 刪除</button>
        </div>
    }
</div>

Application/Views/UsersAdmin/Details.cshtml
@model Application.Models.ApplicationUser

@{
    ViewBag.Title = "帳號詳情";
    Layout = "~/Views/Shared/_AdminLte3.cshtml";
}
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    基本資料
                </div>
                <div class="card-body">
                    <table class="table table-striped table-hover">
                        
                        <tbody>
                            <tr>
                                <th style="width:120px">
                                    帳號名稱
                                </th>
                                <td>
                                    @Html.DisplayFor(model => model.UserName)
                                </td>
                            </tr>
                        </tbody>
                        
                    </table>                    
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    所屬群組
                </div>
                <div class="card-body">
                    @if (ViewBag.GroupNames.Count == 0)
                    {
                        <p>未屬任何群組</p>
                    }
                    else
                    {
                        <table class="table table-borderless">

                            <tbody>
                                @foreach (var item in ViewBag.GroupNames)
                                {
                                    <tr>
                                        <td>
                                            @Html.Encode(item)
                                        </td>
                                    </tr>
                                }
                            </tbody>

                        </table>
                    }
                </div>
            </div>
        </div>
        <div class="col-12">
            <a class="btn btn-warning" href="@Url.Action("Index")"><i class="fas fa-arrow-left"></i>返回</a>
            <a class="btn btn-default" href="@Url.Action("Edit",new { id = Model.Id })"><i class="fas fa-pen"></i>編輯</a>
        </div>
    </div>    
    
</div>

Application/Views/UsersAdmin/Edit.cshtml
@model Application.ViewModels.EditUserViewModel

@{
    ViewBag.Title = "編輯帳號資料";
    Layout = "~/Views/Shared/_AdminLte3.cshtml";
}

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="form-horizontal">

                <div class="card">.
                    <div class="card-header">
                        基本資料
                    </div>
                    <div class="card-body">
                        @Html.ValidationSummary(true)
                        @Html.HiddenFor(model => model.Id)
                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, new { @class = "control-label" })

                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control col-md-4" })
                            @Html.ValidationMessageFor(model => model.Email)

                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        所屬群組
                    </div>
                    <div class="card-body">
                        @foreach (var item in Model.GroupsList)
                        {
                            <div>
                                <label>
                                    <input type="checkbox" name="selectedGroups" value="@item.Value" checked="@item.Selected" class="checkbox-inline mr-1" />
                                    @Html.Encode(item.Text)
                                </label>


                            </div>
                        }
                    </div>
                </div>
                

                <div class="form-group">
                    <a class="btn btn-warning" href="@Url.Action("Index")"><i class="fas fa-arrow-left"></i> 返回</a>
                    <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> 存檔 </button>
                </div>
            </div>
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Application/Views/UsersAdmin/Index.cshtml
@model IEnumerable<Application.Models.ApplicationUser>

@{
    ViewBag.Title = "帳號管理";
    Layout = "~/Views/Shared/_AdminLte3.cshtml";
}


<div class="container-fluid">
    <p>
        <a class="btn btn-primary" href="@Url.Action("Create")">
            <i class="fas fa-plus"></i> 新增帳號
        </a>
    </p>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th style="width:20%;min-width:280px">
                                   
                                </th>
                                <th>
                                    帳號
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <a class="btn btn-default" href="@Url.Action("Edit", new { id = item.Id })"><i class="fas fa-pen"></i> 編輯</a>
                                        <a class="btn btn-info" href="@Url.Action("Details", new { id = item.Id })"><i class="fas fa-eye"></i> 詳情</a>
                                        <a class="btn btn-danger" href="@Url.Action("Delete", new { id = item.Id })"><i class="fas fa-trash"></i> 刪除</a>
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UserName)
                                    </td>

                                </tr>
                            }
                        </tbody>

                        

                    </table>
                </div>
            </div>

        </div>
    </div>
</div>